### ISSUE TITLE
如何获得百度迁徙数据

### ISSUE THREAD

**Issue by LeiBAI** [NCP-VIS/map_visualization#1]
你好，谢谢你们精彩的分析和展示，请问“从武汉出发，到各个城市的人口数量”数据怎么可以获得呀？百度迁徙有对应的api吗

**Comment by Shimingyi** [comment]
你好，对应的api是有的：可以参考我们这段简单的爬虫代码，其中几个变量在代码头部定义：https://gist.github.com/Shimingyi/f44f739eca8e33a54ee7bc779c18324c

**Comment by LeiBAI** [comment]
非常感谢
